import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.80.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const youtubeApiKey = Deno.env.get("YOUTUBE_API_KEY");

interface CaptionTrack {
  code: string;
  name: string;
  isAutoGenerated: boolean;
}

// Check if a video has captions in specific language
async function checkVideoCaptions(videoId: string, targetLanguage?: string): Promise<{ 
  available: boolean; 
  languages: CaptionTrack[];
  hasTargetLanguage: boolean;
}> {
  try {
    const videoPageResponse = await fetch(`https://www.youtube.com/watch?v=${videoId}`);
    
    if (!videoPageResponse.ok) {
      return { available: false, languages: [], hasTargetLanguage: false };
    }
    
    const html = await videoPageResponse.text();
    const captionTracksMatch = html.match(/"captionTracks":\s*(\[.*?\])/);
    
    if (!captionTracksMatch) {
      return { available: false, languages: [], hasTargetLanguage: false };
    }
    
    const captionTracks = JSON.parse(captionTracksMatch[1]);
    const languages: CaptionTrack[] = captionTracks.map((track: any) => ({
      code: track.languageCode,
      name: track.name?.simpleText || track.languageCode,
      isAutoGenerated: track.kind === 'asr'
    }));

    const hasTargetLanguage = targetLanguage 
      ? languages.some(lang => lang.code === targetLanguage)
      : false;
    
    return { 
      available: languages.length > 0, 
      languages,
      hasTargetLanguage
    };
  } catch (error) {
    console.error("Error checking captions:", error);
    return { available: false, languages: [], hasTargetLanguage: false };
  }
}

serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Get authenticated user
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return new Response(
        JSON.stringify({ error: "Missing authorization header" }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const token = authHeader.replace("Bearer ", "");
    const { data: { user }, error: authError } = await supabase.auth.getUser(token);

    if (authError || !user) {
      return new Response(
        JSON.stringify({ error: "Unauthorized" }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    if (!youtubeApiKey) {
      return new Response(
        JSON.stringify({ error: "YouTube API key not configured" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const { query, language, maxResults = 10 } = await req.json();

    if (!query || query.trim().length === 0) {
      return new Response(
        JSON.stringify({ error: "Search query is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    console.log(`Searching YouTube for: "${query}", language: ${language || 'any'}, max: ${maxResults}`);

    // Search for videos using YouTube Data API v3
    const searchUrl = new URL("https://www.googleapis.com/youtube/v3/search");
    searchUrl.searchParams.append("part", "snippet");
    searchUrl.searchParams.append("q", query);
    searchUrl.searchParams.append("type", "video");
    searchUrl.searchParams.append("videoCaption", "closedCaption"); // Only videos with captions
    searchUrl.searchParams.append("maxResults", maxResults.toString());
    searchUrl.searchParams.append("key", youtubeApiKey);

    if (language) {
      searchUrl.searchParams.append("relevanceLanguage", language);
    }

    const searchResponse = await fetch(searchUrl.toString());

    if (!searchResponse.ok) {
      const errorText = await searchResponse.text();
      console.error("YouTube API error:", errorText);
      return new Response(
        JSON.stringify({ error: "YouTube search failed", details: errorText }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const searchData = await searchResponse.json();

    if (!searchData.items || searchData.items.length === 0) {
      return new Response(
        JSON.stringify({ results: [], message: "No videos found with captions" }),
        { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Process results and check caption availability
    const results = await Promise.all(
      searchData.items.map(async (item: any) => {
        const videoId = item.id.videoId;
        const captionInfo = await checkVideoCaptions(videoId, language);

        return {
          videoId,
          title: item.snippet.title,
          description: item.snippet.description,
          thumbnail: item.snippet.thumbnails.medium.url,
          channelTitle: item.snippet.channelTitle,
          publishedAt: item.snippet.publishedAt,
          url: `https://www.youtube.com/watch?v=${videoId}`,
          captions: {
            available: captionInfo.available,
            languages: captionInfo.languages,
            hasRequestedLanguage: captionInfo.hasTargetLanguage
          }
        };
      })
    );

    // Filter to only include videos with captions (and optionally in target language)
    const filteredResults = language
      ? results.filter(r => r.captions.hasRequestedLanguage)
      : results.filter(r => r.captions.available);

    console.log(`Found ${filteredResults.length} videos with captions`);

    return new Response(
      JSON.stringify({ 
        results: filteredResults,
        totalResults: filteredResults.length,
        searchQuery: query,
        targetLanguage: language
      }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error: any) {
    console.error("Error in search-youtube function:", error);
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
